volumes:
  ckan_storage:
  pg_data:
  solr_data:
  pip_cache:
  site_packages:
  vscode_server:

services:

  ckan-dev:
    build:
      context: ckan/
      dockerfile: Dockerfile.dev
      args:
        - TZ=${TZ}
    env_file:
      - .env
    links:
      - db
      - solr
      - redis
    ports:
      - "0.0.0.0:${CKAN_PORT_HOST}:${CKAN_PORT}"
    volumes:
      - ckan_storage:/var/lib/ckan
      - ./src:/srv/app/src_extensions
      - pip_cache:/root/.cache/pip
      - site_packages:/usr/lib/python3.10/site-packages
      - vscode_server:/root/.vscode-server
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "-qO", "/dev/null", "http://localhost:5000" ]
    networks:
      - dbnet
      - solrnet
      - redisnet
      - ckannet

  datapusher:
    container_name: datapusher-plus
    build:
      context: datapusher-plus/
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8800:8800"
    networks:
      - dbnet

  db:
    build:
      context: postgresql/
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - CKAN_DB_USER
      - CKAN_DB_PASSWORD
      - CKAN_DB
      - DATASTORE_READONLY_USER
      - DATASTORE_READONLY_PASSWORD
      - DATASTORE_DB
      - DB_DATAPUSHER_JOBS
      - DB_DATAPUSHER_JOBS_USER
      - DB_DATAPUSHER_JOBS_PASS
      - DB_DATAPUSHER_PASS
      - DB_DATAPUSHER_USER
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}", "-d", "${POSTGRES_DB}" ]
    networks:
      - dbnet

  solr:
    image: ckan/ckan-solr:${SOLR_IMAGE_VERSION}
    volumes:
      - solr_data:/var/solr
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "wget", "-qO", "/dev/null", "http://localhost:8983/solr/" ]
    networks:
      - solrnet

  redis:
    image: redis:${REDIS_VERSION}
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "redis-cli", "-e", "QUIT" ]
    networks:
      - redisnet

networks:
  ckannet:
  solrnet:
    internal: true
  dbnet:
    internal: true
  redisnet:
    internal: true