#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    CREATE ROLE "$CKAN_DB_USER" NOSUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD '$CKAN_DB_PASSWORD';
    CREATE DATABASE "$CKAN_DB" OWNER "$CKAN_DB_USER" ENCODING 'utf-8';

    CREATE ROLE datapusher LOGIN PASSWORD 'YOURPASSWORD';
    GRANT CREATE, CONNECT, TEMPORARY, SUPERUSER ON DATABASE datastore TO datapusher;
    GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public TO datapusher;

    CREATE ROLE datapusher_jobs NOSUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD 'datapusher_jobs_pass';
    CREATE DATABASE datapusher_jobs OWNER datapusher_jobs ENCODING 'utf-8';
EOSQL
