#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" <<-EOSQL
    ALTER ROLE $DB_DATAPUSHER_USER SUPERUSER;
    GRANT CREATE, CONNECT, TEMPORARY ON DATABASE $DATASTORE_DB TO $DB_DATAPUSHER_USER;
    GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE ON ALL TABLES IN SCHEMA public TO $DB_DATAPUSHER_USER;

    CREATE ROLE $DB_DATAPUSHER_JOBS_USER NOSUPERUSER CREATEDB CREATEROLE LOGIN PASSWORD '$DB_DATAPUSHER_JOBS_PASS';
    CREATE DATABASE $DB_DATAPUSHER_JOBS OWNER '$DB_DATAPUSHER_JOBS_USER' ENCODING 'utf-8';
EOSQL